### ISSUE TITLE
Window Leak

### ISSUE THREAD

**Issue by richarth** [bbindreiter/PushNotificationTester_App#2]
Firstly thanks for the great app.  I used it to check my device and after doing so I received the following error in my device log:

```
04-27 13:37:09.839 3699-3699/? E/WindowManager: android.view.WindowLeaked: Activity com.firstrowria.pushnotificationtester.activities.MainActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{86502d1 V.E..... R....... 0,0-720,665} that was originally added here
                                                    at android.view.ViewRootImpl.<init>(ViewRootImpl.java:363)
                                                    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:271)
                                                    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
                                                    at android.app.Dialog.show(Dialog.java:298)
                                                    at com.firstrowria.pushnotificationtester.activities.MainActivity.onOptionsItemSelected(MainActivity.java:326)
                                                    at android.app.Activity.onMenuItemSelected(Activity.java:2885)
                                                    at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:325)
                                                    at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:147)
                                                    at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
                                                    at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
                                                    at android.support.v7.internal.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:73)
                                                    at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:180)
                                                    at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:761)
                                                    at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
                                                    at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
                                                    at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
                                                    at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
                                                    at android.support.v7.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:191)
                                                    at android.widget.AdapterView.performItemClick(AdapterView.java:305)
                                                    at android.widget.AbsListView.performItemClick(AbsListView.java:1148)
                                                    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3059)
                                                    at android.widget.AbsListView$3.run(AbsListView.java:3866)
                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                    at android.os.Looper.loop(Looper.java:135)
                                                    at android.app.ActivityThread.main(ActivityThread.java:5294)
                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by bbindreiter** [comment]
Thank you for taking the time to submit this issue. It's been fixed in 8c0074dd4a34ac43a0b62027fa2984152c0158fe
